"""Remove redditor creation date

Revision ID: 570da81081db
Revises: 5cbeec1e7a17
Create Date: 2023-04-03 12:13:32.043447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570da81081db'
down_revision = '5cbeec1e7a17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redditor', 'created_utc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redditor', sa.Column('created_utc', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
